name: Deploy to Amazon S3

on:
  push:
    branches: [ "master" ]
    
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp . s3://${{ secrets.S3_BUCKET }}/* --recursive \
          --exclude ".git/*" \
          --exclude "node_modules/*" \
          --exclude "coverage/*" \
          --exclude ".github/*"
